name: pragma_cat_breeds
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.2
  go_router: ^6.5.0
  lottie: ^2.3.0
  equatable: ^2.0.3
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^4.0.0
  http: ^1.5.0
  dio: ^5.9.0
  dartz: ^0.10.1
  get_it: ^7.6.0
  sqflite: ^2.3.3
  path: ^1.9.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/pragma_logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lottie/
    - assets/images/